#!/bin/bash
# https://www.destroyallsoftware.com/screencasts/catalog/fast-tests-with-and-without-rails
 
set -e
 
need_rails=1

if [ $# -gt 0 ]; then # we have args
    filename=$1
    # Remove trailing line numbers from filename, e.g. spec/my_spec.rb:33
    grep_filename=`echo $1 | sed 's/:.*$//g'` 
    set +e; grep -r '\bspec_helper\b' $grep_filename
    if [ $? -eq 1 ]; then # no match; we have a stand-alone spec
        need_rails=''
    fi
else # we have no args
    filename='spec'
fi
 
command="./bin/cucumber"
 
if [ $need_rails ]; then
    command="spring $command"
fi

 
RAILS_ENV=test $command $filename
